// Code generated by github.com/LiskHQ/lisk-engine/pkg/codec/gen; DO NOT EDIT.

package smt

import (
	"github.com/LiskHQ/lisk-engine/pkg/codec"
)

func (e *Proof) Encode() ([]byte, error) {
	writer := codec.NewWriter()
	if err := writer.WriteBytesArray(1, codec.HexArrayToBytesArray(e.SiblingHashes)); err != nil {
		return nil, err
	}
	{
		for _, val := range e.Queries {
			if val != nil {
				if err := writer.WriteEncodable(2, val); err != nil {
					return nil, err
				}
			}
		}
	}
	return writer.Result(), nil
}

func (e *Proof) MustEncode() []byte {
	encoded, err := e.Encode()
	if err != nil {
		panic(err)
	}
	return encoded
}

func (e *Proof) Decode(data []byte) error {
	reader := codec.NewReader(data)
	return e.DecodeFromReader(reader)
}

func (e *Proof) MustDecode(data []byte) {
	if err := e.Decode(data); err != nil {
		panic(err)
	}
}

func (e *Proof) DecodeStrict(data []byte) error {
	reader := codec.NewReader(data)
	if err := e.DecodeStrictFromReader(reader); err != nil {
		return err
	}
	if reader.HasUnreadBytes() {
		return codec.ErrUnreadBytes
	}
	return nil
}

func (e *Proof) DecodeFromReader(reader *codec.Reader) error {
	{
		val, err := reader.ReadBytesArray(1)
		if err != nil {
			return err
		}
		e.SiblingHashes = codec.BytesArrayToHexArray(val)
	}
	{
		vals, err := reader.ReadDecodables(2, func() codec.DecodableReader { return new(QueryProof) })
		if err != nil {
			return err
		}
		r := make([]*QueryProof, len(vals))
		for i, v := range vals {
			r[i] = v.(*QueryProof)
		}
		e.Queries = r
	}
	return nil
}

func (e *Proof) DecodeStrictFromReader(reader *codec.Reader) error {
	{
		val, err := reader.ReadBytesArray(1)
		if err != nil {
			return err
		}
		e.SiblingHashes = codec.BytesArrayToHexArray(val)
	}
	{
		vals, err := reader.ReadDecodables(2, func() codec.DecodableReader { return new(QueryProof) })
		if err != nil {
			return err
		}
		r := make([]*QueryProof, len(vals))
		for i, v := range vals {
			r[i] = v.(*QueryProof)
		}
		e.Queries = r
	}
	return nil
}

func (e *QueryProof) Encode() ([]byte, error) {
	writer := codec.NewWriter()
	if err := writer.WriteBytes(1, e.Key); err != nil {
		return nil, err
	}
	if err := writer.WriteBytes(2, e.Value); err != nil {
		return nil, err
	}
	if err := writer.WriteBytes(3, e.Bitmap); err != nil {
		return nil, err
	}
	return writer.Result(), nil
}

func (e *QueryProof) MustEncode() []byte {
	encoded, err := e.Encode()
	if err != nil {
		panic(err)
	}
	return encoded
}

func (e *QueryProof) Decode(data []byte) error {
	reader := codec.NewReader(data)
	return e.DecodeFromReader(reader)
}

func (e *QueryProof) MustDecode(data []byte) {
	if err := e.Decode(data); err != nil {
		panic(err)
	}
}

func (e *QueryProof) DecodeStrict(data []byte) error {
	reader := codec.NewReader(data)
	if err := e.DecodeStrictFromReader(reader); err != nil {
		return err
	}
	if reader.HasUnreadBytes() {
		return codec.ErrUnreadBytes
	}
	return nil
}

func (e *QueryProof) DecodeFromReader(reader *codec.Reader) error {
	{
		val, err := reader.ReadBytes(1, false)
		if err != nil {
			return err
		}
		e.Key = val
	}
	{
		val, err := reader.ReadBytes(2, false)
		if err != nil {
			return err
		}
		e.Value = val
	}
	{
		val, err := reader.ReadBytes(3, false)
		if err != nil {
			return err
		}
		e.Bitmap = val
	}
	return nil
}

func (e *QueryProof) DecodeStrictFromReader(reader *codec.Reader) error {
	{
		val, err := reader.ReadBytes(1, true)
		if err != nil {
			return err
		}
		e.Key = val
	}
	{
		val, err := reader.ReadBytes(2, true)
		if err != nil {
			return err
		}
		e.Value = val
	}
	{
		val, err := reader.ReadBytes(3, true)
		if err != nil {
			return err
		}
		e.Bitmap = val
	}
	return nil
}
