// Code generated by github.com/LiskHQ/lisk-engine/pkg/codec/gen; DO NOT EDIT.

package p2p

import (
	"github.com/LiskHQ/lisk-engine/pkg/codec"
)

func (e *RequestMsg) Encode() ([]byte, error) {
	writer := codec.NewWriter()
	if err := writer.WriteString(1, e.ID); err != nil {
		return nil, err
	}
	if err := writer.WriteInt(2, e.Timestamp); err != nil {
		return nil, err
	}
	if err := writer.WriteString(3, e.PeerID); err != nil {
		return nil, err
	}
	if err := writer.WriteString(4, e.Procedure); err != nil {
		return nil, err
	}
	if err := writer.WriteBytes(5, e.Data); err != nil {
		return nil, err
	}
	return writer.Result(), nil
}

func (e *RequestMsg) MustEncode() []byte {
	encoded, err := e.Encode()
	if err != nil {
		panic(err)
	}
	return encoded
}

func (e *RequestMsg) Decode(data []byte) error {
	reader := codec.NewReader(data)
	return e.DecodeFromReader(reader)
}

func (e *RequestMsg) MustDecode(data []byte) {
	if err := e.Decode(data); err != nil {
		panic(err)
	}
}

func (e *RequestMsg) DecodeStrict(data []byte) error {
	reader := codec.NewReader(data)
	if err := e.DecodeStrictFromReader(reader); err != nil {
		return err
	}
	if reader.HasUnreadBytes() {
		return codec.ErrUnreadBytes
	}
	return nil
}

func (e *RequestMsg) DecodeFromReader(reader *codec.Reader) error {
	{
		val, err := reader.ReadString(1, false)
		if err != nil {
			return err
		}
		e.ID = val
	}
	{
		val, err := reader.ReadInt(2, false)
		if err != nil {
			return err
		}
		e.Timestamp = val
	}
	{
		val, err := reader.ReadString(3, false)
		if err != nil {
			return err
		}
		e.PeerID = val
	}
	{
		val, err := reader.ReadString(4, false)
		if err != nil {
			return err
		}
		e.Procedure = val
	}
	{
		val, err := reader.ReadBytes(5, false)
		if err != nil {
			return err
		}
		e.Data = val
	}
	return nil
}

func (e *RequestMsg) DecodeStrictFromReader(reader *codec.Reader) error {
	{
		val, err := reader.ReadString(1, true)
		if err != nil {
			return err
		}
		e.ID = val
	}
	{
		val, err := reader.ReadInt(2, true)
		if err != nil {
			return err
		}
		e.Timestamp = val
	}
	{
		val, err := reader.ReadString(3, true)
		if err != nil {
			return err
		}
		e.PeerID = val
	}
	{
		val, err := reader.ReadString(4, true)
		if err != nil {
			return err
		}
		e.Procedure = val
	}
	{
		val, err := reader.ReadBytes(5, true)
		if err != nil {
			return err
		}
		e.Data = val
	}
	return nil
}

func (e *ResponseMsg) Encode() ([]byte, error) {
	writer := codec.NewWriter()
	if err := writer.WriteString(1, e.ID); err != nil {
		return nil, err
	}
	if err := writer.WriteInt(2, e.Timestamp); err != nil {
		return nil, err
	}
	if err := writer.WriteString(3, e.PeerID); err != nil {
		return nil, err
	}
	if err := writer.WriteBytes(4, e.Data); err != nil {
		return nil, err
	}
	return writer.Result(), nil
}

func (e *ResponseMsg) MustEncode() []byte {
	encoded, err := e.Encode()
	if err != nil {
		panic(err)
	}
	return encoded
}

func (e *ResponseMsg) Decode(data []byte) error {
	reader := codec.NewReader(data)
	return e.DecodeFromReader(reader)
}

func (e *ResponseMsg) MustDecode(data []byte) {
	if err := e.Decode(data); err != nil {
		panic(err)
	}
}

func (e *ResponseMsg) DecodeStrict(data []byte) error {
	reader := codec.NewReader(data)
	if err := e.DecodeStrictFromReader(reader); err != nil {
		return err
	}
	if reader.HasUnreadBytes() {
		return codec.ErrUnreadBytes
	}
	return nil
}

func (e *ResponseMsg) DecodeFromReader(reader *codec.Reader) error {
	{
		val, err := reader.ReadString(1, false)
		if err != nil {
			return err
		}
		e.ID = val
	}
	{
		val, err := reader.ReadInt(2, false)
		if err != nil {
			return err
		}
		e.Timestamp = val
	}
	{
		val, err := reader.ReadString(3, false)
		if err != nil {
			return err
		}
		e.PeerID = val
	}
	{
		val, err := reader.ReadBytes(4, false)
		if err != nil {
			return err
		}
		e.Data = val
	}
	return nil
}

func (e *ResponseMsg) DecodeStrictFromReader(reader *codec.Reader) error {
	{
		val, err := reader.ReadString(1, true)
		if err != nil {
			return err
		}
		e.ID = val
	}
	{
		val, err := reader.ReadInt(2, true)
		if err != nil {
			return err
		}
		e.Timestamp = val
	}
	{
		val, err := reader.ReadString(3, true)
		if err != nil {
			return err
		}
		e.PeerID = val
	}
	{
		val, err := reader.ReadBytes(4, true)
		if err != nil {
			return err
		}
		e.Data = val
	}
	return nil
}

func (e *Message) Encode() ([]byte, error) {
	writer := codec.NewWriter()
	if err := writer.WriteInt(1, e.Timestamp); err != nil {
		return nil, err
	}
	if err := writer.WriteBytes(2, e.Data); err != nil {
		return nil, err
	}
	return writer.Result(), nil
}

func (e *Message) MustEncode() []byte {
	encoded, err := e.Encode()
	if err != nil {
		panic(err)
	}
	return encoded
}

func (e *Message) Decode(data []byte) error {
	reader := codec.NewReader(data)
	return e.DecodeFromReader(reader)
}

func (e *Message) MustDecode(data []byte) {
	if err := e.Decode(data); err != nil {
		panic(err)
	}
}

func (e *Message) DecodeStrict(data []byte) error {
	reader := codec.NewReader(data)
	if err := e.DecodeStrictFromReader(reader); err != nil {
		return err
	}
	if reader.HasUnreadBytes() {
		return codec.ErrUnreadBytes
	}
	return nil
}

func (e *Message) DecodeFromReader(reader *codec.Reader) error {
	{
		val, err := reader.ReadInt(1, false)
		if err != nil {
			return err
		}
		e.Timestamp = val
	}
	{
		val, err := reader.ReadBytes(2, false)
		if err != nil {
			return err
		}
		e.Data = val
	}
	return nil
}

func (e *Message) DecodeStrictFromReader(reader *codec.Reader) error {
	{
		val, err := reader.ReadInt(1, true)
		if err != nil {
			return err
		}
		e.Timestamp = val
	}
	{
		val, err := reader.ReadBytes(2, true)
		if err != nil {
			return err
		}
		e.Data = val
	}
	return nil
}
