// Code generated by github.com/LiskHQ/lisk-engine/pkg/codec/gen; DO NOT EDIT.

package diffdb

import (
	"github.com/LiskHQ/lisk-engine/pkg/codec"
)

func (e *KV) Encode() ([]byte, error) {
	writer := codec.NewWriter()
	if err := writer.WriteBytes(1, e.Key); err != nil {
		return nil, err
	}
	if err := writer.WriteBytes(2, e.Value); err != nil {
		return nil, err
	}
	return writer.Result(), nil
}

func (e *KV) MustEncode() []byte {
	encoded, err := e.Encode()
	if err != nil {
		panic(err)
	}
	return encoded
}

func (e *KV) Decode(data []byte) error {
	reader := codec.NewReader(data)
	return e.DecodeFromReader(reader)
}

func (e *KV) MustDecode(data []byte) {
	if err := e.Decode(data); err != nil {
		panic(err)
	}
}

func (e *KV) DecodeStrict(data []byte) error {
	reader := codec.NewReader(data)
	if err := e.DecodeStrictFromReader(reader); err != nil {
		return err
	}
	if reader.HasUnreadBytes() {
		return codec.ErrUnreadBytes
	}
	return nil
}

func (e *KV) DecodeFromReader(reader *codec.Reader) error {
	{
		val, err := reader.ReadBytes(1, false)
		if err != nil {
			return err
		}
		e.Key = val
	}
	{
		val, err := reader.ReadBytes(2, false)
		if err != nil {
			return err
		}
		e.Value = val
	}
	return nil
}

func (e *KV) DecodeStrictFromReader(reader *codec.Reader) error {
	{
		val, err := reader.ReadBytes(1, true)
		if err != nil {
			return err
		}
		e.Key = val
	}
	{
		val, err := reader.ReadBytes(2, true)
		if err != nil {
			return err
		}
		e.Value = val
	}
	return nil
}

func (e *Diff) Encode() ([]byte, error) {
	writer := codec.NewWriter()
	if err := writer.WriteBytesArray(1, e.Added); err != nil {
		return nil, err
	}
	{
		for _, val := range e.Updated {
			if val != nil {
				if err := writer.WriteEncodable(2, val); err != nil {
					return nil, err
				}
			}
		}
	}
	{
		for _, val := range e.Deleted {
			if val != nil {
				if err := writer.WriteEncodable(3, val); err != nil {
					return nil, err
				}
			}
		}
	}
	return writer.Result(), nil
}

func (e *Diff) MustEncode() []byte {
	encoded, err := e.Encode()
	if err != nil {
		panic(err)
	}
	return encoded
}

func (e *Diff) Decode(data []byte) error {
	reader := codec.NewReader(data)
	return e.DecodeFromReader(reader)
}

func (e *Diff) MustDecode(data []byte) {
	if err := e.Decode(data); err != nil {
		panic(err)
	}
}

func (e *Diff) DecodeStrict(data []byte) error {
	reader := codec.NewReader(data)
	if err := e.DecodeStrictFromReader(reader); err != nil {
		return err
	}
	if reader.HasUnreadBytes() {
		return codec.ErrUnreadBytes
	}
	return nil
}

func (e *Diff) DecodeFromReader(reader *codec.Reader) error {
	{
		val, err := reader.ReadBytesArray(1)
		if err != nil {
			return err
		}
		e.Added = val
	}
	{
		vals, err := reader.ReadDecodables(2, func() codec.DecodableReader { return new(KV) })
		if err != nil {
			return err
		}
		r := make([]*KV, len(vals))
		for i, v := range vals {
			r[i] = v.(*KV)
		}
		e.Updated = r
	}
	{
		vals, err := reader.ReadDecodables(3, func() codec.DecodableReader { return new(KV) })
		if err != nil {
			return err
		}
		r := make([]*KV, len(vals))
		for i, v := range vals {
			r[i] = v.(*KV)
		}
		e.Deleted = r
	}
	return nil
}

func (e *Diff) DecodeStrictFromReader(reader *codec.Reader) error {
	{
		val, err := reader.ReadBytesArray(1)
		if err != nil {
			return err
		}
		e.Added = val
	}
	{
		vals, err := reader.ReadDecodables(2, func() codec.DecodableReader { return new(KV) })
		if err != nil {
			return err
		}
		r := make([]*KV, len(vals))
		for i, v := range vals {
			r[i] = v.(*KV)
		}
		e.Updated = r
	}
	{
		vals, err := reader.ReadDecodables(3, func() codec.DecodableReader { return new(KV) })
		if err != nil {
			return err
		}
		r := make([]*KV, len(vals))
		for i, v := range vals {
			r[i] = v.(*KV)
		}
		e.Deleted = r
	}
	return nil
}
