// Code generated by github.com/LiskHQ/lisk-engine/pkg/codec/gen; DO NOT EDIT.

package txpool

import (
	"github.com/LiskHQ/lisk-engine/pkg/codec"
)

func (e *PostTransactionAnnouncementEvent) Encode() ([]byte, error) {
	writer := codec.NewWriter()
	if err := writer.WriteBytesArray(1, codec.HexArrayToBytesArray(e.TransactionIDs)); err != nil {
		return nil, err
	}
	return writer.Result(), nil
}

func (e *PostTransactionAnnouncementEvent) MustEncode() []byte {
	encoded, err := e.Encode()
	if err != nil {
		panic(err)
	}
	return encoded
}

func (e *PostTransactionAnnouncementEvent) Decode(data []byte) error {
	reader := codec.NewReader(data)
	return e.DecodeFromReader(reader)
}

func (e *PostTransactionAnnouncementEvent) MustDecode(data []byte) {
	if err := e.Decode(data); err != nil {
		panic(err)
	}
}

func (e *PostTransactionAnnouncementEvent) DecodeStrict(data []byte) error {
	reader := codec.NewReader(data)
	if err := e.DecodeStrictFromReader(reader); err != nil {
		return err
	}
	if reader.HasUnreadBytes() {
		return codec.ErrUnreadBytes
	}
	return nil
}

func (e *PostTransactionAnnouncementEvent) DecodeFromReader(reader *codec.Reader) error {
	{
		val, err := reader.ReadBytesArray(1)
		if err != nil {
			return err
		}
		e.TransactionIDs = codec.BytesArrayToHexArray(val)
	}
	return nil
}

func (e *PostTransactionAnnouncementEvent) DecodeStrictFromReader(reader *codec.Reader) error {
	{
		val, err := reader.ReadBytesArray(1)
		if err != nil {
			return err
		}
		e.TransactionIDs = codec.BytesArrayToHexArray(val)
	}
	return nil
}
