// Code generated by github.com/LiskHQ/lisk-engine/pkg/codec/gen; DO NOT EDIT.

package txpool

import (
	"github.com/LiskHQ/lisk-engine/pkg/blockchain"
	"github.com/LiskHQ/lisk-engine/pkg/codec"
)

func (e *GetTransactionsResponse) Encode() []byte {
	writer := codec.NewWriter()
	{
		for _, val := range e.Transactions {
			if val != nil {
				writer.WriteEncodable(1, val)
			}
		}
	}
	return writer.Result()
}

func (e *GetTransactionsResponse) Decode(data []byte) error {
	reader := codec.NewReader(data)
	return e.DecodeFromReader(reader)
}

func (e *GetTransactionsResponse) MustDecode(data []byte) {
	if err := e.Decode(data); err != nil {
		panic(err)
	}
}

func (e *GetTransactionsResponse) DecodeStrict(data []byte) error {
	reader := codec.NewReader(data)
	if err := e.DecodeStrictFromReader(reader); err != nil {
		return err
	}
	if reader.HasUnreadBytes() {
		return codec.ErrUnreadBytes
	}
	return nil
}

func (e *GetTransactionsResponse) DecodeFromReader(reader *codec.Reader) error {
	{
		vals, err := reader.ReadDecodables(1, func() codec.DecodableReader { return new(blockchain.Transaction) })
		if err != nil {
			return err
		}
		r := make([]*blockchain.Transaction, len(vals))
		for i, v := range vals {
			r[i] = v.(*blockchain.Transaction)
		}
		e.Transactions = r
	}
	return nil
}

func (e *GetTransactionsResponse) DecodeStrictFromReader(reader *codec.Reader) error {
	{
		vals, err := reader.ReadDecodables(1, func() codec.DecodableReader { return new(blockchain.Transaction) })
		if err != nil {
			return err
		}
		r := make([]*blockchain.Transaction, len(vals))
		for i, v := range vals {
			r[i] = v.(*blockchain.Transaction)
		}
		e.Transactions = r
	}
	return nil
}
