// Code generated by github.com/LiskHQ/lisk-engine/pkg/codec/gen; DO NOT EDIT.

package mock

import (
	"github.com/LiskHQ/lisk-engine/pkg/codec"
)

func (e *Pair) Encode() []byte {
	writer := codec.NewWriter()
	writer.WriteBytes(1, e.Key)
	writer.WriteBytes(2, e.Value)
	return writer.Result()
}

func (e *Pair) Decode(data []byte) error {
	reader := codec.NewReader(data)
	return e.DecodeFromReader(reader)
}

func (e *Pair) MustDecode(data []byte) {
	if err := e.Decode(data); err != nil {
		panic(err)
	}
}

func (e *Pair) DecodeStrict(data []byte) error {
	reader := codec.NewReader(data)
	if err := e.DecodeStrictFromReader(reader); err != nil {
		return err
	}
	if reader.HasUnreadBytes() {
		return codec.ErrUnreadBytes
	}
	return nil
}

func (e *Pair) DecodeFromReader(reader *codec.Reader) error {
	{
		val, err := reader.ReadBytes(1, false)
		if err != nil {
			return err
		}
		e.Key = val
	}
	{
		val, err := reader.ReadBytes(2, false)
		if err != nil {
			return err
		}
		e.Value = val
	}
	return nil
}

func (e *Pair) DecodeStrictFromReader(reader *codec.Reader) error {
	{
		val, err := reader.ReadBytes(1, true)
		if err != nil {
			return err
		}
		e.Key = val
	}
	{
		val, err := reader.ReadBytes(2, true)
		if err != nil {
			return err
		}
		e.Value = val
	}
	return nil
}

func (e *DataSetParams) Encode() []byte {
	writer := codec.NewWriter()
	{
		for _, val := range e.Pairs {
			if val != nil {
				writer.WriteEncodable(1, val)
			}
		}
	}
	writer.WriteBool(2, e.Hash)
	return writer.Result()
}

func (e *DataSetParams) Decode(data []byte) error {
	reader := codec.NewReader(data)
	return e.DecodeFromReader(reader)
}

func (e *DataSetParams) MustDecode(data []byte) {
	if err := e.Decode(data); err != nil {
		panic(err)
	}
}

func (e *DataSetParams) DecodeStrict(data []byte) error {
	reader := codec.NewReader(data)
	if err := e.DecodeStrictFromReader(reader); err != nil {
		return err
	}
	if reader.HasUnreadBytes() {
		return codec.ErrUnreadBytes
	}
	return nil
}

func (e *DataSetParams) DecodeFromReader(reader *codec.Reader) error {
	{
		vals, err := reader.ReadDecodables(1, func() codec.DecodableReader { return new(Pair) })
		if err != nil {
			return err
		}
		r := make([]*Pair, len(vals))
		for i, v := range vals {
			r[i] = v.(*Pair)
		}
		e.Pairs = r
	}
	{
		val, err := reader.ReadBool(2, false)
		if err != nil {
			return err
		}
		e.Hash = val
	}
	return nil
}

func (e *DataSetParams) DecodeStrictFromReader(reader *codec.Reader) error {
	{
		vals, err := reader.ReadDecodables(1, func() codec.DecodableReader { return new(Pair) })
		if err != nil {
			return err
		}
		r := make([]*Pair, len(vals))
		for i, v := range vals {
			r[i] = v.(*Pair)
		}
		e.Pairs = r
	}
	{
		val, err := reader.ReadBool(2, true)
		if err != nil {
			return err
		}
		e.Hash = val
	}
	return nil
}
