// Code generated by github.com/LiskHQ/lisk-engine/pkg/codec/gen; DO NOT EDIT.

package p2p

import (
	"github.com/LiskHQ/lisk-engine/pkg/codec"
)

func (e *NodeInfo) Encode() ([]byte, error) {
	writer := codec.NewWriter()
	if err := writer.WriteString(1, e.ChainID); err != nil {
		return nil, err
	}
	if err := writer.WriteString(2, e.NetworkVersion); err != nil {
		return nil, err
	}
	if err := writer.WriteString(3, e.Nonce); err != nil {
		return nil, err
	}
	if err := writer.WriteBool(4, e.AdvertiseAddress); err != nil {
		return nil, err
	}
	if err := writer.WriteBytes(5, e.Options); err != nil {
		return nil, err
	}
	return writer.Result(), nil
}

func (e *NodeInfo) MustEncode() []byte {
	encoded, err := e.Encode()
	if err != nil {
		panic(err)
	}
	return encoded
}

func (e *NodeInfo) Decode(data []byte) error {
	reader := codec.NewReader(data)
	return e.DecodeFromReader(reader)
}

func (e *NodeInfo) MustDecode(data []byte) {
	if err := e.Decode(data); err != nil {
		panic(err)
	}
}

func (e *NodeInfo) DecodeStrict(data []byte) error {
	reader := codec.NewReader(data)
	if err := e.DecodeStrictFromReader(reader); err != nil {
		return err
	}
	if reader.HasUnreadBytes() {
		return codec.ErrUnreadBytes
	}
	return nil
}

func (e *NodeInfo) DecodeFromReader(reader *codec.Reader) error {
	{
		val, err := reader.ReadString(1, false)
		if err != nil {
			return err
		}
		e.ChainID = val
	}
	{
		val, err := reader.ReadString(2, false)
		if err != nil {
			return err
		}
		e.NetworkVersion = val
	}
	{
		val, err := reader.ReadString(3, false)
		if err != nil {
			return err
		}
		e.Nonce = val
	}
	{
		val, err := reader.ReadBool(4, false)
		if err != nil {
			return err
		}
		e.AdvertiseAddress = val
	}
	{
		val, err := reader.ReadBytes(5, false)
		if err != nil {
			return err
		}
		e.Options = val
	}
	return nil
}

func (e *NodeInfo) DecodeStrictFromReader(reader *codec.Reader) error {
	{
		val, err := reader.ReadString(1, true)
		if err != nil {
			return err
		}
		e.ChainID = val
	}
	{
		val, err := reader.ReadString(2, true)
		if err != nil {
			return err
		}
		e.NetworkVersion = val
	}
	{
		val, err := reader.ReadString(3, true)
		if err != nil {
			return err
		}
		e.Nonce = val
	}
	{
		val, err := reader.ReadBool(4, true)
		if err != nil {
			return err
		}
		e.AdvertiseAddress = val
	}
	{
		val, err := reader.ReadBytes(5, true)
		if err != nil {
			return err
		}
		e.Options = val
	}
	return nil
}
