// Code generated by github.com/LiskHQ/lisk-engine/pkg/codec/gen; DO NOT EDIT.

package validator

import (
	"github.com/LiskHQ/lisk-engine/pkg/codec"
)

func (e *hashValidator) Encode() ([]byte, error) {
	writer := codec.NewWriter()
	if err := writer.WriteBytes(1, e.blsKey); err != nil {
		return nil, err
	}
	if err := writer.WriteUInt(2, e.bftWeight); err != nil {
		return nil, err
	}
	return writer.Result(), nil
}

func (e *hashValidator) MustEncode() []byte {
	encoded, err := e.Encode()
	if err != nil {
		panic(err)
	}
	return encoded
}

func (e *hashValidator) Decode(data []byte) error {
	reader := codec.NewReader(data)
	return e.DecodeFromReader(reader)
}

func (e *hashValidator) MustDecode(data []byte) {
	if err := e.Decode(data); err != nil {
		panic(err)
	}
}

func (e *hashValidator) DecodeStrict(data []byte) error {
	reader := codec.NewReader(data)
	if err := e.DecodeStrictFromReader(reader); err != nil {
		return err
	}
	if reader.HasUnreadBytes() {
		return codec.ErrUnreadBytes
	}
	return nil
}

func (e *hashValidator) DecodeFromReader(reader *codec.Reader) error {
	{
		val, err := reader.ReadBytes(1, false)
		if err != nil {
			return err
		}
		e.blsKey = val
	}
	{
		val, err := reader.ReadUInt(2, false)
		if err != nil {
			return err
		}
		e.bftWeight = val
	}
	return nil
}

func (e *hashValidator) DecodeStrictFromReader(reader *codec.Reader) error {
	{
		val, err := reader.ReadBytes(1, true)
		if err != nil {
			return err
		}
		e.blsKey = val
	}
	{
		val, err := reader.ReadUInt(2, true)
		if err != nil {
			return err
		}
		e.bftWeight = val
	}
	return nil
}

func (e *validatrorsHashData) Encode() ([]byte, error) {
	writer := codec.NewWriter()
	{
		for _, val := range e.activeValidators {
			if val != nil {
				if err := writer.WriteEncodable(1, val); err != nil {
					return nil, err
				}
			}
		}
	}
	if err := writer.WriteUInt(2, e.certificateThreshold); err != nil {
		return nil, err
	}
	return writer.Result(), nil
}

func (e *validatrorsHashData) MustEncode() []byte {
	encoded, err := e.Encode()
	if err != nil {
		panic(err)
	}
	return encoded
}

func (e *validatrorsHashData) Decode(data []byte) error {
	reader := codec.NewReader(data)
	return e.DecodeFromReader(reader)
}

func (e *validatrorsHashData) MustDecode(data []byte) {
	if err := e.Decode(data); err != nil {
		panic(err)
	}
}

func (e *validatrorsHashData) DecodeStrict(data []byte) error {
	reader := codec.NewReader(data)
	if err := e.DecodeStrictFromReader(reader); err != nil {
		return err
	}
	if reader.HasUnreadBytes() {
		return codec.ErrUnreadBytes
	}
	return nil
}

func (e *validatrorsHashData) DecodeFromReader(reader *codec.Reader) error {
	{
		vals, err := reader.ReadDecodables(1, func() codec.DecodableReader { return new(hashValidator) })
		if err != nil {
			return err
		}
		r := make([]*hashValidator, len(vals))
		for i, v := range vals {
			r[i] = v.(*hashValidator)
		}
		e.activeValidators = r
	}
	{
		val, err := reader.ReadUInt(2, false)
		if err != nil {
			return err
		}
		e.certificateThreshold = val
	}
	return nil
}

func (e *validatrorsHashData) DecodeStrictFromReader(reader *codec.Reader) error {
	{
		vals, err := reader.ReadDecodables(1, func() codec.DecodableReader { return new(hashValidator) })
		if err != nil {
			return err
		}
		r := make([]*hashValidator, len(vals))
		for i, v := range vals {
			r[i] = v.(*hashValidator)
		}
		e.activeValidators = r
	}
	{
		val, err := reader.ReadUInt(2, true)
		if err != nil {
			return err
		}
		e.certificateThreshold = val
	}
	return nil
}
