// Code generated by github.com/LiskHQ/lisk-engine/pkg/codec/gen; DO NOT EDIT.

package rmt

import (
	"github.com/LiskHQ/lisk-engine/pkg/codec"
)

func (e *Proof) Encode() []byte {
	writer := codec.NewWriter()
	writer.WriteUInt(1, e.Size)
	writer.WriteUInts(2, e.Idxs)
	writer.WriteBytesArray(3, e.SiblingHashes)
	return writer.Result()
}

func (e *Proof) Decode(data []byte) error {
	reader := codec.NewReader(data)
	return e.DecodeFromReader(reader)
}

func (e *Proof) MustDecode(data []byte) {
	if err := e.Decode(data); err != nil {
		panic(err)
	}
}

func (e *Proof) DecodeStrict(data []byte) error {
	reader := codec.NewReader(data)
	if err := e.DecodeStrictFromReader(reader); err != nil {
		return err
	}
	if reader.HasUnreadBytes() {
		return codec.ErrUnreadBytes
	}
	return nil
}

func (e *Proof) DecodeFromReader(reader *codec.Reader) error {
	{
		val, err := reader.ReadUInt(1, false)
		if err != nil {
			return err
		}
		e.Size = val
	}
	{
		val, err := reader.ReadUInts(2)
		if err != nil {
			return err
		}
		e.Idxs = val
	}
	{
		val, err := reader.ReadBytesArray(3)
		if err != nil {
			return err
		}
		e.SiblingHashes = val
	}
	return nil
}

func (e *Proof) DecodeStrictFromReader(reader *codec.Reader) error {
	{
		val, err := reader.ReadUInt(1, true)
		if err != nil {
			return err
		}
		e.Size = val
	}
	{
		val, err := reader.ReadUInts(2)
		if err != nil {
			return err
		}
		e.Idxs = val
	}
	{
		val, err := reader.ReadBytesArray(3)
		if err != nil {
			return err
		}
		e.SiblingHashes = val
	}
	return nil
}
